#!/usr/bin/env bash
# Concatenate the migrations and product seed into a single setup.sql.
# Run from the database/ directory after editing any migration.
set -euo pipefail
cd "$(dirname "$0")"

FILES=(
  migrations/001_create_profiles.sql
  migrations/002_create_products.sql
  migrations/003_create_orders.sql
  migrations/004_add_indexes.sql
  migrations/005_rls_policies.sql
  migrations/006_place_order_function.sql
  seeds/002_products.sql
)

{
  echo "-- Hak Shop — complete database setup."
  echo "-- Paste this whole file into the Supabase SQL Editor and run it once."
  echo "-- Generated by database/build-setup.sh — edit the migrations, not this."
  echo "-- Safe to re-run."
  echo
  for f in "${FILES[@]}"; do
    echo "-- ============================================================"
    echo "-- $f"
    echo "-- ============================================================"
    cat "$f"
    echo
  done
} > setup.sql

echo "setup.sql rebuilt ($(wc -l < setup.sql | tr -d ' ') lines)"
