-- Hak Shop — complete database setup.
-- Paste this whole file into the Supabase SQL Editor and run it once.
-- Generated by database/build-setup.sh — edit the migrations, not this.
-- Safe to re-run.

-- ============================================================
-- migrations/001_create_profiles.sql
-- ============================================================
-- Customer and staff profiles, one row per Supabase auth user.
--
-- Supabase owns `auth.users`; this table holds the store-specific fields and
-- the role flag that the admin pages check.

do $$ begin
  create type public.user_role as enum ('customer', 'admin');
exception when duplicate_object then null;
end $$;

create table if not exists public.profiles (
  id          uuid primary key references auth.users (id) on delete cascade,
  name        text not null default '',
  student_id  text not null default '',
  batch       text not null default '',
  phone       text not null default '',
  dorm        text not null default 'Dorm B',
  room        text not null default '',
  role        public.user_role not null default 'customer',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

comment on table public.profiles is 'Store profile for each authenticated user.';

-- Create the profile automatically whenever someone signs up. Runs as the
-- definer so it can write to a table the new user cannot yet see.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'name', ''))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Role lookup used by the RLS policies below. SECURITY DEFINER so that
-- checking "am I an admin?" does not re-enter the profiles policies and
-- recurse infinitely.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

-- ============================================================
-- migrations/002_create_products.sql
-- ============================================================
-- Product catalog.
--
-- The id is the human-readable slug the frontend already uses
-- (e.g. "coca-cola"), which keeps mock data and live data interchangeable.

do $$ begin
  create type public.product_category as enum
    ('Drinks', 'Noodles', 'Chips', 'Biscuits', 'Sweets');
exception when duplicate_object then null;
end $$;

create table if not exists public.products (
  id          text primary key,
  name        text not null,
  description text not null default '',
  price       numeric(10, 2) not null check (price >= 0),
  stock       integer not null default 0 check (stock >= 0),
  category    public.product_category not null,
  image       text not null default '',
  promo       boolean not null default false,
  popular     boolean not null default false,
  -- Soft delete: hidden from the storefront but kept for order history.
  active      boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

comment on table public.products is 'Snacks and drinks available in the store.';

-- ============================================================
-- migrations/003_create_orders.sql
-- ============================================================
-- Orders and their line items.
--
-- user_id is nullable on purpose: students can order as guests straight from
-- the QR code without creating an account.

do $$ begin
  create type public.order_status as enum
    ('pending', 'preparing', 'delivering', 'delivered', 'cancelled');
exception when duplicate_object then null;
end $$;

create table if not exists public.orders (
  id            uuid primary key default gen_random_uuid(),
  order_number  text not null unique,
  user_id       uuid references auth.users (id) on delete set null,

  -- Delivery details captured at checkout.
  customer_name text not null,
  student_id    text not null default '',
  batch         text not null default '',
  phone         text not null,
  dorm          text not null,
  room          text not null,
  note          text not null default '',

  payment       text not null default 'cash',
  status        public.order_status not null default 'pending',

  subtotal      numeric(10, 2) not null default 0,
  delivery      numeric(10, 2) not null default 0,
  total         numeric(10, 2) not null default 0,

  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- Line items copy name/price so historical orders stay correct even if the
-- product is later renamed, repriced or removed.
create table if not exists public.order_items (
  id         uuid primary key default gen_random_uuid(),
  order_id   uuid not null references public.orders (id) on delete cascade,
  product_id text references public.products (id) on delete set null,
  name       text not null,
  image      text not null default '',
  price      numeric(10, 2) not null,
  quantity   integer not null check (quantity > 0)
);

comment on table public.orders is 'Customer orders, including guest orders.';
comment on table public.order_items is 'Line items, denormalised for history.';

-- ============================================================
-- migrations/004_add_indexes.sql
-- ============================================================
-- Lookup and foreign-key indexes.

-- Storefront browses by category and hides inactive rows.
create index if not exists products_active_category_idx
  on public.products (active, category);

-- Admin order list is newest-first, often filtered by status.
create index if not exists orders_created_at_idx
  on public.orders (created_at desc);

create index if not exists orders_status_idx
  on public.orders (status);

-- "My orders" on the account page.
create index if not exists orders_user_id_idx
  on public.orders (user_id);

-- Every order detail view joins its items.
create index if not exists order_items_order_id_idx
  on public.order_items (order_id);

create index if not exists profiles_role_idx
  on public.profiles (role);

-- Keep updated_at honest.
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_touch on public.products;
create trigger products_touch before update on public.products
  for each row execute function public.touch_updated_at();

drop trigger if exists orders_touch on public.orders;
create trigger orders_touch before update on public.orders
  for each row execute function public.touch_updated_at();

drop trigger if exists profiles_touch on public.profiles;
create trigger profiles_touch before update on public.profiles
  for each row execute function public.touch_updated_at();

-- ============================================================
-- migrations/005_rls_policies.sql
-- ============================================================
-- Row level security.
--
-- The anon key ships to every browser, so RLS is the only thing protecting
-- this data. Every table is locked by default and opened deliberately.

alter table public.profiles    enable row level security;
alter table public.products    enable row level security;
alter table public.orders      enable row level security;
alter table public.order_items enable row level security;

-- ---------------- profiles ----------------
drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own on public.profiles
  for select using (id = auth.uid() or public.is_admin());

drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own on public.profiles
  for update using (id = auth.uid() or public.is_admin())
  with check (id = auth.uid() or public.is_admin());

-- ---------------- products ----------------
-- The storefront is public: anyone with the QR code can browse without
-- signing in. Only staff may change the catalog.
drop policy if exists products_select_public on public.products;
create policy products_select_public on public.products
  for select using (active or public.is_admin());

drop policy if exists products_write_admin on public.products;
create policy products_write_admin on public.products
  for all using (public.is_admin()) with check (public.is_admin());

-- ---------------- orders ----------------
-- Guests may place an order, but only the owner or staff may read it back.
drop policy if exists orders_insert_any on public.orders;
create policy orders_insert_any on public.orders
  for insert with check (user_id is null or user_id = auth.uid());

drop policy if exists orders_select_own on public.orders;
create policy orders_select_own on public.orders
  for select using (
    public.is_admin() or (user_id is not null and user_id = auth.uid())
  );

drop policy if exists orders_update_admin on public.orders;
create policy orders_update_admin on public.orders
  for update using (public.is_admin()) with check (public.is_admin());

drop policy if exists orders_delete_admin on public.orders;
create policy orders_delete_admin on public.orders
  for delete using (public.is_admin());

-- ---------------- order_items ----------------
drop policy if exists order_items_insert_any on public.order_items;
create policy order_items_insert_any on public.order_items
  for insert with check (
    exists (
      select 1 from public.orders o
      where o.id = order_id
        and (o.user_id is null or o.user_id = auth.uid() or public.is_admin())
    )
  );

drop policy if exists order_items_select_own on public.order_items;
create policy order_items_select_own on public.order_items
  for select using (
    exists (
      select 1 from public.orders o
      where o.id = order_id
        and (public.is_admin() or (o.user_id is not null and o.user_id = auth.uid()))
    )
  );

-- ============================================================
-- migrations/006_place_order_function.sql
-- ============================================================
-- Atomic order placement.
--
-- Everything an order touches happens in one transaction: stock is checked
-- and decremented, the order and its items are written, and a readable order
-- number is issued. Prices are read from the products table, never from the
-- client, so a tampered request cannot change what an order costs.

create sequence if not exists public.order_number_seq start 1001;

create or replace function public.place_order(
  p_customer jsonb,
  p_items    jsonb,
  p_payment  text default 'cash'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order_id     uuid := gen_random_uuid();
  v_order_number text;
  v_subtotal     numeric(10, 2) := 0;
  v_delivery     numeric(10, 2) := 0;
  v_item         jsonb;
  v_product      public.products%rowtype;
  v_quantity     integer;
begin
  if p_items is null or jsonb_array_length(p_items) = 0 then
    raise exception 'Your bag is empty.' using errcode = 'P0001';
  end if;

  if coalesce(p_customer ->> 'name', '') = '' then
    raise exception 'A name is required.' using errcode = 'P0001';
  end if;

  if coalesce(p_customer ->> 'phone', '') = '' then
    raise exception 'A phone number is required.' using errcode = 'P0001';
  end if;

  v_order_number := 'HS-' || nextval('public.order_number_seq')::text;

  -- Lock each product row so two students cannot buy the same last packet.
  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_quantity := coalesce((v_item ->> 'quantity')::integer, 0);

    if v_quantity <= 0 then
      raise exception 'Quantity must be at least 1.' using errcode = 'P0001';
    end if;

    select * into v_product
    from public.products
    where id = (v_item ->> 'product_id')
    for update;

    if not found then
      raise exception 'Product % is no longer available.',
        (v_item ->> 'product_id') using errcode = 'P0001';
    end if;

    if not v_product.active then
      raise exception '% is no longer available.', v_product.name
        using errcode = 'P0001';
    end if;

    if v_product.stock < v_quantity then
      raise exception 'Only % left of %.', v_product.stock, v_product.name
        using errcode = 'P0001';
    end if;

    v_subtotal := v_subtotal + (v_product.price * v_quantity);
  end loop;

  insert into public.orders (
    id, order_number, user_id, customer_name, student_id, batch,
    phone, dorm, room, note, payment, status, subtotal, delivery, total
  )
  values (
    v_order_id,
    v_order_number,
    auth.uid(),
    p_customer ->> 'name',
    coalesce(p_customer ->> 'student_id', ''),
    coalesce(p_customer ->> 'batch', ''),
    p_customer ->> 'phone',
    coalesce(p_customer ->> 'dorm', ''),
    coalesce(p_customer ->> 'room', ''),
    coalesce(p_customer ->> 'note', ''),
    coalesce(p_payment, 'cash'),
    'pending',
    v_subtotal,
    v_delivery,
    v_subtotal + v_delivery
  );

  -- Second pass: write the lines and take the stock.
  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_quantity := (v_item ->> 'quantity')::integer;

    select * into v_product
    from public.products
    where id = (v_item ->> 'product_id');

    insert into public.order_items
      (order_id, product_id, name, image, price, quantity)
    values
      (v_order_id, v_product.id, v_product.name, v_product.image,
       v_product.price, v_quantity);

    update public.products
    set stock = stock - v_quantity
    where id = v_product.id;
  end loop;

  return jsonb_build_object(
    'id',           v_order_id,
    'order_number', v_order_number,
    'status',       'pending',
    'subtotal',     v_subtotal,
    'delivery',     v_delivery,
    'total',        v_subtotal + v_delivery
  );
end;
$$;

-- Guests check out straight from the QR code, so anon needs to call this.
grant execute on function public.place_order(jsonb, jsonb, text) to anon, authenticated;

-- ============================================================
-- seeds/002_products.sql
-- ============================================================
-- Seed the snack catalog.
--
-- Generated from frontend/data/products.ts so the seed and the offline
-- fallback data stay identical. Safe to re-run: existing rows are updated.

insert into public.products
  (id, name, description, price, stock, category, image, promo, popular)
values
  ('coca-cola', 'Coca Cola', 'Chilled 330ml can', 0.75, 30, 'Drinks', '🥤', true, true),
  ('nescafe-latte', 'Nescafé Latte', 'Ready to drink 240ml', 1.25, 12, 'Drinks', '☕', false, true),
  ('mineral-water', 'Mineral Water', 'Chilled 500ml bottle', 0.4, 60, 'Drinks', '💧', false, true),
  ('orange-juice', 'Orange Juice', 'No sugar added, 250ml', 1.1, 18, 'Drinks', '🧃', false, false),
  ('iced-tea-lemon', 'Lemon Iced Tea', 'Refreshing 500ml bottle', 0.85, 26, 'Drinks', '🍋', false, false),
  ('milk-choco', 'Chocolate Milk', 'Cold 200ml carton', 0.95, 21, 'Drinks', '🥛', false, false),
  ('energy-drink', 'Energy Drink', 'For late-night study, 250ml', 1.5, 9, 'Drinks', '⚡', false, false),
  ('soy-milk', 'Soy Milk', 'Lightly sweetened, 300ml', 0.9, 15, 'Drinks', '🫘', false, false),
  ('mama-tom-yum', 'Mama Noodles', 'Tom yum shrimp flavour', 0.6, 40, 'Noodles', '🍜', false, true),
  ('indomie-goreng', 'Indomie Goreng', 'Fried noodles, classic', 0.7, 35, 'Noodles', '🍲', false, true),
  ('cup-noodle-chicken', 'Cup Noodle Chicken', 'Just add hot water', 1.0, 22, 'Noodles', '🥡', false, false),
  ('kimchi-ramen', 'Kimchi Ramen', 'Spicy Korean style', 1.3, 14, 'Noodles', '🌶️', false, false),
  ('beef-instant-noodle', 'Beef Noodles', 'Rich beef broth pack', 0.8, 27, 'Noodles', '🐄', false, false),
  ('glass-noodle-soup', 'Glass Noodle Soup', 'Light and quick', 0.95, 0, 'Noodles', '🍥', false, false),
  ('lays-classic', 'Lay''s Classic', 'Salted potato chips', 1.1, 18, 'Chips', '🍟', false, true),
  ('cheese-ring', 'Cheese Ring', 'Crispy corn snack rings', 0.9, 22, 'Chips', '🧀', false, false),
  ('seaweed-crisps', 'Seaweed Crisps', 'Roasted, lightly salted', 1.2, 16, 'Chips', '🍘', false, false),
  ('prawn-crackers', 'Prawn Crackers', 'Crunchy shrimp flavour', 0.85, 24, 'Chips', '🍤', false, false),
  ('tortilla-chips', 'Tortilla Chips', 'Corn chips with a kick', 1.35, 11, 'Chips', '🌽', false, false),
  ('popcorn-butter', 'Butter Popcorn', 'Ready-to-eat 60g bag', 1.0, 19, 'Chips', '🍿', false, false),
  ('oreo-biscuit', 'Oreo Biscuit', 'Chocolate sandwich cookies', 0.8, 24, 'Biscuits', '🍪', false, true),
  ('pocky-strawberry', 'Pocky Strawberry', 'Biscuit sticks, 45g pack', 1.2, 15, 'Biscuits', '🍓', false, false),
  ('cream-wafer', 'Cream Wafer', 'Layered vanilla wafer', 0.65, 30, 'Biscuits', '🧇', false, false),
  ('butter-cookies', 'Butter Cookies', 'Danish style tin, small', 1.6, 8, 'Biscuits', '🥮', false, false),
  ('cracker-salt', 'Salt Crackers', 'Light and crispy', 0.55, 33, 'Biscuits', '🧂', false, false),
  ('snickers', 'Snickers Bar', 'Peanut caramel chocolate', 1.0, 20, 'Sweets', '🍫', false, true),
  ('gummy-bears', 'Gummy Bears', 'Fruit chews, 80g bag', 1.05, 16, 'Sweets', '🐻', true, false),
  ('lollipop-mix', 'Lollipop Mix', 'Assorted fruit flavours', 0.35, 50, 'Sweets', '🍭', false, false),
  ('mochi-red-bean', 'Red Bean Mochi', 'Soft rice cake, 4 pieces', 1.45, 10, 'Sweets', '🍡', false, false),
  ('donut-sugar', 'Sugar Donut', 'Baked fresh this morning', 0.9, 12, 'Sweets', '🍩', false, false),
  ('ice-cream-cup', 'Ice Cream Cup', 'Vanilla, 100ml', 1.25, 0, 'Sweets', '🍨', false, false)
on conflict (id) do update set
  name        = excluded.name,
  description = excluded.description,
  price       = excluded.price,
  category    = excluded.category,
  image       = excluded.image,
  promo       = excluded.promo,
  popular     = excluded.popular;

